### ISSUE TITLE
encrypted multipart backup aws3 issue

### ISSUE THREAD

**Issue by dbccomm** [watchfulli/XCloner-Wordpress#177] opened 2021-11-14 00:31 UTC
Generate Backup (multipart)
   Encrypted
   Send to S3
   Delete Local

Only last part ends up on S3
Local Files do not get deleted

When Encrypted is not enabled
Everything works fine

**Comment by vdrover** [comment] 2022-08-12 12:58
Closing as duplicate of #193.

**Closed by vdrover** 2022-08-12 12:58 UTC
Labels: testing
